name: Manual Workflow with Options

on:
    workflow_dispatch:
      inputs:
        environment:
          description: "Option to choose"
          required: true
          default: "deploy"
          type: choice # to choose when triggering if not specified we will have to write the options ourself
          options:
              - deploy
              - test
              - delete
              

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Print input values
          run: echo "Workflow runs with option ${{ inputs.environment }}"

