on :
  schedule:
    - cron: "35 * * * *"

jobs :
  periodic-task:
    runs-on : ubuntu_latest
    steps :
            - name : "printing periodic task"
              run : echo "periodic task"
    
    
