name: "Periodic Task Workflow"

on:
  schedule:
    - cron: "38 * * * *"  # runs at the 35th minute of every hour

jobs:
  periodic-task:
    runs-on: ubuntu-latest
    steps:
      - name: "Printing periodic task"
        run: echo "periodic task"
